version: '3.8'

services:
  app-blue:
    image: ghcr.io/jacobsin12/sast-sonar:latest
    container_name: app-blue
    environment:
      - PORT=8080
    ports:
      - "8080:8080" # Esto mapea el puerto del servidor al del contenedor
    restart: always

  app-green:
    image: ghcr.io/jacobsin12/sast-sonar:latest
    container_name: app-green
    environment:
      - PORT=8081
    ports:
      - "8081:8081" # Esto abre el puerto 8081 hacia afuera
    restart: always

  # Monitoreo se queda en Producción para ver los recursos de esta máquina
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus 
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana 
    ports:
      - "3000:3000" # Lo regresé al 3000 para que sea más fácil entrar
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always

volumes:
  prometheus_data:
  grafana_data: