upstream backend_servers {
    # Cambiamos el nombre del contenedor por la IP del servidor de Producción
    server 34.51.85.205:8081;
}

server {
    listen 80;

    location / {
        proxy_pass http://backend_servers;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        add_header X-Deployment-Color "green" always;
    }

    location /sonar/ {
        proxy_pass http://34.51.85.205:9000; # IP de Producción
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port 80;

        proxy_cookie_path / /sonar/;
        proxy_redirect off;
        proxy_buffering off;
    }
}